DROP TABLE IF EXISTS pokedex CASCADE;

CREATE TABLE pokedex(
	id INT AUTO_INCREMENT,
	moves VARCHAR(255) NOT NULL,
	name VARCHAR(255) NOT NULL,
	type VARCHAR(255) NOT NULL,
	weakness VARCHAR(255) NOT NULL,
	PRIMARY KEY(id)
	);